services:
  cms-dev:
    container_name: pkrbt-cms-dev
    image: pkrbt-cms-dev:latest
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - 1338:1337
    volumes:
      - ./vars/cms-public:/cms/public:rw
