# See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
when@dev: &dev
  zenstruck_foundry:
    # Whether to auto-refresh proxies by default (https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh)
    # auto_refresh_proxies: true
    make_factory:
      default_namespace: 'Paroki\\Fixtures\\Factory'

when@test: *dev
