controllers:
  resource:
    path: ../src/Controller/
    namespace: Paroki\Controller
  type: attribute

api_login_check:
  path: /auth/login-check

google:
  resource:
    path: ../src/Bridge/Google/Controller/
    namespace: Paroki\Bridge\Google\Controller
  type: attribute
