name: Synchronize Repository

on:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.PAT }}
jobs:
  gitlab:
    name: GitLab
    runs-on: ubuntu-latest
    steps:
      - uses: keninkujovic/gitlab-sync@2.0.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          username: ${{ secrets.GITLAB_USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
